import {
  Row,
  Col,
  Menu,
  Tabs,
  Card,
  Space,
  Progress,
  ConfigProvider,
  Input,
  Button,
  Radio,
  Modal,
  Popover,
  Dropdown,
  Avatar,
  Breadcrumb,
  Spin,
  Tooltip,
  Divider,
  Skeleton,
  message,
  Steps,
  Empty,
  Form,
  Result,
  Popconfirm,
  Upload,
  Cascader,
  Rate,
  AutoComplete,
  Badge,
  Descriptions,
  InputNumber,
  Slider,
  Anchor,
  List,
  PageHeader,
  Statistic,
  TimePicker,
  Typography,
  Tree,
  Drawer,
  Alert,
  Layout,
  Table,
  DatePicker,
  Select,
  Switch,
  Checkbox,
  Tag,
  Pagination,
  notification,
  Carousel
} from 'ant-design-vue'

const antDesign = (app) => {
  app.use(Menu)
  app.use(Cascader)
  app.use(Upload)
  app.use(Rate)
  app.use(AutoComplete)
  app.use(Result)
  app.use(Badge)
  app.use(Popconfirm)
  app.use(Descriptions)
  app.use(InputNumber)
  app.use(Slider)
  app.use(Anchor)
  app.use(List)
  app.use(PageHeader)
  app.use(Statistic)
  app.use(TimePicker)
  app.use(Typography)
  app.use(Space)
  app.use(Tree)
  app.use(Drawer)
  app.use(Alert)
  app.use(Layout)
  app.use(Card)
  app.use(Form)
  app.use(Table)
  app.use(DatePicker)
  app.use(Select)
  app.use(Switch)
  app.use(Steps)
  app.use(ConfigProvider)
  app.use(Input)
  app.use(Button)
  app.use(Radio)
  app.use(Checkbox)
  app.use(Row)
  app.use(Col)
  app.use(Modal)
  app.use(Tabs)
  app.use(Popover)
  app.use(Dropdown)
  app.use(Avatar)
  app.use(Breadcrumb)
  app.use(Spin)
  app.use(Tooltip)
  app.use(Tag)
  app.use(Divider)
  app.use(Progress)
  app.use(Skeleton)
  app.use(Empty)
  app.use(Pagination)
  app.use(notification)
  app.use(Carousel)
  message.config({
    duration: 2,
    maxCount: 1
  })
}

export default antDesign
